apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "mysql" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
spec:
  serviceName: database-service
  replicas: 1
  selector:
    matchLabels:
      {{- include "mesa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        {{- include "mesa.labels" . | nindent 8 }}
        app.kubernetes.io/name: mysql
      annotations:
        {{- include "mesa.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "mesa.resourceName" (dict "suffix" "mysql" .) }}
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mesa.resourceName" (dict "suffix" "mysql-secret" .) }}
                  key: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/data
            - name: config-map-custom
              mountPath: /etc/mysql/conf.d
      serviceAccountName: {{ .Values.mysql.service_account }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "mesa.resourceName" (dict "suffix" "mysql-data" .) }}
        - name: config-map-custom
          configMap:
            name: {{ include "mesa.resourceName" (dict "suffix" "mysql-config" .) }}
            items:
              - key: custom.cnf
                path: custom.cnf
