owner: GomezTek
git-repo: helm-charts
package-path: .cr-release-packages
index-path: .
charts-repo: https://gomeztek.github.io/helm-charts
remote: origin
pages-branch: gh-pages
push: true
sign: false
skip-existing: true
