remote: origin
target-branch: main
chart-dirs:
  - gtk-mesa-chart
validate-maintainers: true
validate-chart-schema: true
validate-yaml: true
check-version-increment: true
helm-extra-args: "--timeout 600s"
