replicaCount: 1

global:
  company: demo
  environment: dev
  team: platform

# Add defaults for testing
mysql:
  image: mysql:5.7.38
  pvc_size: 1Gi
  storage_class: standard
  service_account: sa-mysql

redis:
  service_account: sa-redis

backhouseweb:
  image: gomeztek/backhouse:latest
  replicas: 1
  service_account: sa-web
  resources:
    limits:
      cpu: "0.5"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 256Mi

fronthouseweb:
  image: gomeztek/fronthouse:latest
  replicas: 1
  service_account: sa-web
  resources:
    limits:
      cpu: "1.0"
      memory: 1Gi
    requests:
      cpu: "0.5"
      memory: 512Mi

ingress:
  className: nginx-external
  backhouse:
    hosts:
      - host: staff.demo.local
    tls:
      secretName: staff-tls
      hosts:
        - staff.demo.local
  fronthouse:
    hosts:
      - host: orders.demo.local
    tls:
      secretName: orders-tls
      hosts:
        - orders.demo.local

# Argo Rollouts configuration
argo-rollouts:
  enabled: true
  dashboard:
    enabled: true
