global:
  company: 
  environment: production
  docker_registry_secret: gtk-docker-hub-registry

mysql:
  image: mysql:5.7.38
  pvc_size: 10Gi
  secret_name: mysql-secret
  service_account: sa-mysql

redis:
  image: redis:6.2.7
  replicas: 1
  service_account: sa-redis

backhouseweb:
  image: gomeztek/flash:v3.6.1-hf2
  replicas: 2
  service_account: sa-web
  resources:
    limits:
      cpu: "0.5"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 256Mi

fronthouseweb:
  image: gomeztek/flash:v3.6.1-hf2
  replicas: 2
  service_account: sa-web
  resources:
    limits:
      cpu: "0.5"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 256Mi

ingress:
  className: nginx-external
  backhouse:
    hosts:
      - host: backhouse.gtkpos.com
    tls:
      secretName: backhouse-tls
      hosts:
        - backhouse.gtkpos.com
  fronthouse:
    hosts:
      - host: store.gtkpos.com
    tls:
      secretName: fronthouse-tls
      hosts:
        - store.gtkpos.com

# Argo Rollouts configuration
rolloutConfig:
  strategy:
    blueGreen:
      activeService: backhouse-service
      previewService: backhouse-preview-service
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 300  # 5 minutes delay before scaling down old version


