global:
  company: mesa  # Set a default company name to avoid empty resource names
  environment: production
  docker_registry_secret: gtk-docker-hub-registry

mysql:
  image:
    repository: mysql
    tag: 5.7.38
    pullPolicy: IfNotPresent
  service_account: sa-mysql  # Add explicit service account name
  replicaCount: 1
  args:
    - --basedir=/var/lib/mysql
    - --datadir=/var/lib/mysql/data
    - --console
    - --innodb-use-native-aio=0
    - --ignore-db-dir=lost+found
    - --explicit_defaults_for_timestamp=1
    - --innodb-buffer-pool-size=256M
    - --innodb_buffer_pool_instances=2
  timezone: America/Los_Angeles
  nodeSelector: {}
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "250m"
      memory: 384Mi
  config: |
    [mysqld]
    bind-address     = 0.0.0.0
    sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    max_allowed_packet=256M
    innodb_log_file_size=1GB

    #transaction-isolation=READ-COMMITTED
    #character-set-server=utf8
    #collation-server=utf8_bin
    #default-storage-engine=INNODB

    [mysqldump]
    column-statistics=0

    #END CONFIG

redis:
  image: redis:6.2.7
  replicas: 1
  service_account: sa-redis

backhouseweb:
  image: gomeztek/flash:v3.6.1-hf2
  replicas: 2
  service_account: sa-web
  resources:
    limits:
      cpu: "0.5"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 256Mi

fronthouseweb:
  image: gomeztek/flash:v3.6.1-hf2
  replicas: 2
  service_account: sa-web
  resources:
    limits:
      cpu: "0.5"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 256Mi

ingress:
  className: nginx-external
  backhouse:
    hosts:
      - host: backhouse.gtkpos.com
    tls:
      secretName: backhouse-tls
      hosts:
        - backhouse.gtkpos.com
  fronthouse:
    hosts:
      - host: store.gtkpos.com
    tls:
      secretName: fronthouse-tls
      hosts:
        - store.gtkpos.com

# Argo Rollouts configuration
rolloutConfig:
  strategy:
    blueGreen:
      activeService: backhouse-service
      previewService: backhouse-preview-service
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 300  # 5 minutes delay before scaling down old version


