apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "mysql-data" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.pvc_size | default "10Gi" }}
  {{- if .Values.mysql.storage_class }}
  storageClassName: {{ .Values.mysql.storage_class }}
  {{- end }}
