apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "mysql-secret" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "secrets" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "aws-secret" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "stripe-secret" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "registry-secret" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data: {}
