{{- /* ServiceAccounts for MySQL, Redis, and Web services */}}
{{- if .Values.mysql.service_account }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mysql.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.redis.service_account }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.backhouseweb.service_account }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backhouseweb.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
    component: staff-portal
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
imagePullSecrets:
- name: {{ .Values.global.docker_registry_secret }}
{{- end }}
{{- if .Values.fronthouseweb.service_account }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fronthouseweb.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
    component: customer-portal
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
imagePullSecrets:
- name: {{ .Values.global.docker_registry_secret }}
{{- end }}
