{{- /* ServiceAccounts for MySQL, Redis, and Web services */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mysql.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backhouseweb.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
    component: staff-portal
imagePullSecrets:
  - name: {{ .Values.global.docker_registry_secret }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fronthouseweb.service_account }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
    component: customer-portal
imagePullSecrets:
  - name: {{ .Values.global.docker_registry_secret }}
