apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "mysql-config" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
    component: database-backup
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
data:
  custom.cnf: |
    {{- .Values.mysql.config | nindent 4 }}
