apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mesa.resourceName" (dict "suffix" "mysql-config" "root" .) }}
  labels:
    {{- include "mesa.labels" . | nindent 4 }}
  annotations:
    {{- include "mesa.annotations" . | nindent 4 }}
data:
  custom.cnf: |-
    [mysqld]
    bind-address     = 0.0.0.0
    sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    max_allowed_packet=256M
    innodb_log_file_size=1GB

    #transaction-isolation=READ-COMMITTED
    #character-set-server=utf8
    #collation-server=utf8_bin
    #default-storage-engine=INNODB

    [mysqldump]
    column-statistics=0

    #END CONFIG
