name: Release Helm Chart

on:
  push:
    branches:
      - main
      - master
      - 'release/*'
    paths:
      - 'gtk-mesa-chart/**'
      - '.github/workflows/helm-release.yaml'
  # Allow manual triggers
  workflow_dispatch:

env:
  CHART_DIR: gtk-mesa-chart
  CHART_REPO_URL: https://${{ github.repository_owner }}.github.io/helm-charts
  CHART_REPO_NAME: gomeztek-charts

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for gh-pages
      packages: write  # Needed for GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Argo Rollouts CRD repo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Set Chart Version
        id: set_version
        run: |
          if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            # For release branches, append git sha
            SHA=$(git rev-parse --short HEAD)
            CHART_VERSION=$(yq eval '.version' ${{ env.CHART_DIR }}/Chart.yaml)
            NEW_VERSION="${CHART_VERSION}-${SHA}"
            yq eval -i '.version = "'${NEW_VERSION}'"' ${{ env.CHART_DIR }}/Chart.yaml
            echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          else
            # For master/main, use version as is
            VERSION=$(yq eval '.version' ${{ env.CHART_DIR }}/Chart.yaml)
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
        with:
          charts_dir: .
          config: .github/cr.yaml

      - name: Package Chart
        run: |
          helm dependency update ${{ env.CHART_DIR }}
          helm package ${{ env.CHART_DIR }}

      # Push to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart to GHCR
        run: |
          VERSION=${{ steps.set_version.outputs.version }}
          helm push mesa-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
