name: Release Helm Chart

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'gtk-mesa-chart/**'
      - '.github/workflows/helm-release.yaml'
  # Allow manual triggers
  workflow_dispatch:

env:
  CHART_DIR: gtk-mesa-chart
  CHART_REPO_URL: https://${{ github.repository_owner }}.github.io/helm-charts
  CHART_REPO_NAME: gomeztek-charts

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for gh-pages
      packages: write  # Needed for GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Argo Rollouts CRD repo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
        with:
          charts_dir: .
          config: .github/cr.yaml

      - name: Generate test values
        run: |
          cp ${{ env.CHART_DIR }}/values.test.yaml ${{ env.CHART_DIR }}/ci/test-values.yaml

      - name: Run tests
        run: |
          helm dependency update ${{ env.CHART_DIR }}
          helm lint ${{ env.CHART_DIR }} --values ${{ env.CHART_DIR }}/ci/test-values.yaml
          helm template test ${{ env.CHART_DIR }} --values ${{ env.CHART_DIR }}/ci/test-values.yaml

      # Optional: Push OCI chart to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart to GHCR
        run: |
          CHART_VERSION=$(helm show chart ${{ env.CHART_DIR }} | grep '^version:' | cut -d' ' -f2)
          helm package ${{ env.CHART_DIR }}
          helm push mesa-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
